//
// Created by Brenty on 17/03/2026.
//

#ifndef INC_9348_CPLUSPLUS_EDUCATIONALGAME_H
#define INC_9348_CPLUSPLUS_EDUCATIONALGAME_H


class EducationalGame
{
};


#endif //INC_9348_CPLUSPLUS_EDUCATIONALGAME_H